### ISSUE TITLE
thread cpal_wasapi_out panicked on Win MSVC

### ISSUE THREAD

**Issue by safelock** [nicolaschan/insanity#5]
![image](https://github.com/user-attachments/assets/432ee7e0-efdf-4fdb-bf4b-29fd0c1fcfd0)

RUST_BACKTRACE=full:

![image](https://github.com/user-attachments/assets/41ac2842-57d9-415e-93d6-43bc9066fa2c)

**Comment by neelayjunnarkar** [comment]
Fixed by https://github.com/nicolaschan/insanity/commit/cb818c22a984bad9b6acf86d771a475ddb2907ba
